/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import SQL.Metodos_SQL;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author romer
 */
public class alta_pedidos extends javax.swing.JFrame {
     Metodos_SQL metodos_SQL = new Metodos_SQL();
  
     String Fk_claveE;
    String fk_claveC;
    String fk_claveP;
    String clave;
    
    /**
     * Creates new form alta_pedidos
     */
    public alta_pedidos() {
      
    
        

    
        
        initComponents();
        
        
        
          setLocationRelativeTo(null);
        setResizable(false);
        setTitle("pasteleria sura");
        setSize(1280,720);
        
        ImageIcon fondo = new ImageIcon("src/imajenes/alta_pedido_edited.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel1_fondo.getWidth()
                ,jLabel1_fondo.getHeight(), Image.SCALE_DEFAULT ));
        jLabel1_fondo.setIcon(icono);
        this.repaint();
        
        //lenar combo box
         this.conbovendedor.setModel(metodos_SQL.obtener_vendedor());
         this.conbocliente.setModel(metodos_SQL.obtener_cliente());
         this.conbopastel1.setModel(metodos_SQL.obtener_pastel());
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ap1 = new javax.swing.JLabel();
        lbl_ap2 = new javax.swing.JLabel();
        conbovendedor = new javax.swing.JComboBox<>();
        conbocliente = new javax.swing.JComboBox<>();
        lbl_ap4 = new javax.swing.JLabel();
        conbopastel1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_ap5 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ap1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_ap1.setForeground(new java.awt.Color(255, 51, 51));
        lbl_ap1.setText("Vendedor:");
        getContentPane().add(lbl_ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 190, 60));

        lbl_ap2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_ap2.setForeground(new java.awt.Color(255, 51, 51));
        lbl_ap2.setText("Clave:");
        getContentPane().add(lbl_ap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 140, 60));

        conbovendedor.setBackground(new java.awt.Color(255, 153, 153));
        conbovendedor.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        conbovendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        conbovendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conbovendedorActionPerformed(evt);
            }
        });
        getContentPane().add(conbovendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 130, 40));

        conbocliente.setBackground(new java.awt.Color(255, 153, 153));
        conbocliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(conbocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 130, 40));

        lbl_ap4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_ap4.setForeground(new java.awt.Color(255, 51, 51));
        lbl_ap4.setText("Pastel:");
        getContentPane().add(lbl_ap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 120, 60));

        conbopastel1.setBackground(new java.awt.Color(255, 153, 153));
        conbopastel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        conbopastel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(conbopastel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 130, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTA DE NUEVOS PEDIDOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 580, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 170, 70));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 170, 70));

        lbl_ap5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_ap5.setForeground(new java.awt.Color(255, 51, 51));
        lbl_ap5.setText("Cliente:");
        getContentPane().add(lbl_ap5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 140, 60));
        getContentPane().add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 230, 50));

        jLabel1_fondo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conbovendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conbovendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conbovendedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        menu_principal nuevaventana = new menu_principal();
        nuevaventana.setVisible(true);

        //para que no se acumulen las ventanas
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //boton guardar
        Fk_claveE = conbovendedor.getSelectedItem().toString();
        fk_claveC = conbocliente.getSelectedItem().toString();
        fk_claveP = conbopastel1.getSelectedItem().toString();
        clave = txtclave.getText();

        metodos_SQL.guardar_datos_pedido(Fk_claveE,fk_claveC,fk_claveP,clave);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alta_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alta_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alta_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alta_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alta_pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conbocliente;
    private javax.swing.JComboBox<String> conbopastel1;
    private javax.swing.JComboBox<String> conbovendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JLabel lbl_ap1;
    private javax.swing.JLabel lbl_ap2;
    private javax.swing.JLabel lbl_ap4;
    private javax.swing.JLabel lbl_ap5;
    private javax.swing.JTextField txtclave;
    // End of variables declaration//GEN-END:variables
}
