/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import SQL.Metodos_SQL;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author romer
 */
public class alta_productos extends javax.swing.JFrame {
 Metodos_SQL metodos_SQL = new Metodos_SQL();
  
    String PK_clienteP;
    String pastel;
    String precio;
    
    
    /**
     * Creates new form alta_productos
     */
    public alta_productos() {
        initComponents();
          setLocationRelativeTo(null);
        setResizable(false);
        setTitle("pasteleria sura");
        setSize(1280,720);
        
        ImageIcon fondo = new ImageIcon("src/imajenes/alta_productos_edited.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel1_fondo.getWidth()
                ,jLabel1_fondo.getHeight(), Image.SCALE_DEFAULT ));
        jLabel1_fondo.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_ap = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        conboprecio = new javax.swing.JComboBox<>();
        lbl_ap1 = new javax.swing.JLabel();
        conbosabor = new javax.swing.JComboBox<>();
        lbl_ap2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTA DE NUEVOS PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 580, 40));

        lbl_ap.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_ap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ap.setText("Precio $ :");
        getContentPane().add(lbl_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 120, 60));

        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });
        getContentPane().add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, 40));

        conboprecio.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        conboprecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "300", "400", "500" }));
        getContentPane().add(conboprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 130, 40));

        lbl_ap1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_ap1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ap1.setText("Clave:");
        getContentPane().add(lbl_ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 80, 60));

        conbosabor.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        conbosabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chocolate", "vainilla", "3 leches", "manjar", "coco" }));
        getContentPane().add(conbosabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 130, 40));

        lbl_ap2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_ap2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ap2.setText("Pastel:");
        getContentPane().add(lbl_ap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 60));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 170, 70));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 170, 70));
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        menu_principal nuevaventana = new menu_principal();
        nuevaventana.setVisible(true);

        //para que no se acumulen las ventanas
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //boton guardar
        PK_clienteP = txt_clave.getText();
        pastel = conbosabor.getSelectedItem().toString();
        precio = conboprecio.getSelectedItem().toString();
        

        metodos_SQL.guardar_datos_productos(PK_clienteP,pastel,precio);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alta_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conboprecio;
    private javax.swing.JComboBox<String> conbosabor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JLabel lbl_ap;
    private javax.swing.JLabel lbl_ap1;
    private javax.swing.JLabel lbl_ap2;
    private javax.swing.JTextField txt_clave;
    // End of variables declaration//GEN-END:variables
}
