/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import SQL.Metodos_SQL;
import SQL.conexion_bd;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author romer
 */
public class baja_clientes extends javax.swing.JFrame {
Metodos_SQL metodos_SQL = new Metodos_SQL();

    /**
     * Creates new form baja_clientes
     */
    public baja_clientes() {
        initComponents();
         setLocationRelativeTo(null);
        setResizable(false);
        setTitle("pasteleria sura");
        setSize(1280,720);
        
        ImageIcon fondo = new ImageIcon("src/imajenes/alta_clientes_edited.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel1_fondo.getWidth()
                ,jLabel1_fondo.getHeight(), Image.SCALE_DEFAULT ));
        jLabel1_fondo.setIcon(icono);
        this.repaint();
    }
 private static Connection  conexion;
      private static PreparedStatement sentencia_preparada;
    private static ResultSet resultados;
    
    public void buscareliminarcliente(String PK_claveC){
    
     try {
         conexion = conexion_bd.conectar();
         String consulta= "SELECT * FROM PASTELERIA.Clientes WHERE PK_claveC = ?";
         sentencia_preparada = conexion.prepareStatement(consulta);
          sentencia_preparada.setString(1, PK_claveC);
         resultados = sentencia_preparada.executeQuery();
         if(resultados.next()){
             lblinformacion.setText("cliente Registrado");
             
            lblnombre3.setText(resultados.getString("nombre"));

             lblap.setText(resultados.getString("apellidop"));
             lblam.setText(resultados.getString("apellidom"));
             lbltelefono.setText(resultados.getString("telefono"));
             lbldomicilio.setText(resultados.getString("domicilio"));
             lbltelefono.setText(resultados.getString("telefono"));
             
             
             
             
         }else{
             lblinformacion.setText("Sin Resultados");
             
           
         }
         conexion.close ();
     } catch (SQLException e){
          System.out.println("Error"+e);
     }finally{
             try {
                 conexion.close();
             } catch (SQLException ex) {
                 
            
                 System.out.println("Error"+ex);
             }

}

 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_clave = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        lblinformacion = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_domicilio = new javax.swing.JLabel();
        lbl_ap = new javax.swing.JLabel();
        lbl_am = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblap = new javax.swing.JLabel();
        lblnombre3 = new javax.swing.JLabel();
        lbldomicilio = new javax.swing.JLabel();
        lblam = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BAJA DE CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 360, 40));

        lbl_clave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_clave.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clave.setText("Clave de empleado:");
        getContentPane().add(lbl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 190, 60));

        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });
        txt_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_claveKeyReleased(evt);
            }
        });
        getContentPane().add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 180, 40));

        lblinformacion.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblinformacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblinformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 390, 70));

        lbl_nombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, 60));

        lbl_telefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("Telefono:");
        getContentPane().add(lbl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 90, 60));

        lbl_domicilio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_domicilio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_domicilio.setText("Domicilio:");
        getContentPane().add(lbl_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 100, 60));

        lbl_ap.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_ap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ap.setText("Apellido Paterno:");
        getContentPane().add(lbl_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 160, 60));

        lbl_am.setBackground(new java.awt.Color(255, 255, 255));
        lbl_am.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_am.setForeground(new java.awt.Color(255, 255, 255));
        lbl_am.setText("Apellido Materno:");
        getContentPane().add(lbl_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 160, 60));

        lbltelefono.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbltelefono.setForeground(new java.awt.Color(255, 51, 51));
        lbltelefono.setText("--");
        getContentPane().add(lbltelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 230, 60));

        lblap.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblap.setForeground(new java.awt.Color(255, 51, 51));
        lblap.setText("--");
        getContentPane().add(lblap, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 230, 60));

        lblnombre3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblnombre3.setForeground(new java.awt.Color(255, 51, 51));
        lblnombre3.setText("--");
        getContentPane().add(lblnombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 230, 60));

        lbldomicilio.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbldomicilio.setForeground(new java.awt.Color(255, 51, 51));
        lbldomicilio.setText("--");
        getContentPane().add(lbldomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 230, 60));

        lblam.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblam.setForeground(new java.awt.Color(255, 51, 51));
        lblam.setText("--");
        getContentPane().add(lblam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 230, 230, 60));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 170, 70));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton1.setText("eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 170, 70));
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void txt_claveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claveKeyReleased

        buscareliminarcliente(txt_clave.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        menu_principal nuevaventana = new menu_principal();
        nuevaventana.setVisible(true);

        //para que no se acumulen las ventanas
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //boton guardar
        metodos_SQL.eliminarcliente(txt_clave.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baja_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baja_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baja_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baja_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baja_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JLabel lbl_am;
    private javax.swing.JLabel lbl_ap;
    private javax.swing.JLabel lbl_clave;
    private javax.swing.JLabel lbl_domicilio;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lblam;
    private javax.swing.JLabel lblap;
    private javax.swing.JLabel lbldomicilio;
    private javax.swing.JLabel lblinformacion;
    private javax.swing.JLabel lblnombre3;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txt_clave;
    // End of variables declaration//GEN-END:variables
}
