/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import SQL.Metodos_SQL;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author romer
 */
public class modificar_empleados extends javax.swing.JFrame {
    Metodos_SQL metodos_SQL = new Metodos_SQL();

    /**
     * Creates new form modificar_empleados
     */
    public modificar_empleados() {
        initComponents();
          setLocationRelativeTo(null);
        setResizable(false);
        setTitle("pasteleria sura");
        setSize(1280,720);
        
        ImageIcon fondo = new ImageIcon("src/imajenes/alta_empleados_edited.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel1_fondo.getWidth()
                ,jLabel1_fondo.getHeight(), Image.SCALE_DEFAULT ));
        jLabel1_fondo.setIcon(icono);
        this.repaint();
    }
    public void validacion() {
    String mensaje = Metodos_SQL.buscarclave(txt_clave.getText());
    
    
    if(mensaje.equals("Existe empleado")){
        lblinformacion.setText("<html><center> empleado encontrado,Se puede actualizar los datos");
        
    }else if(txt_clave.getText().isEmpty()) {
       
        lblinformacion.setText("");
        
    }else{
        // lblinformacion.setText("No se encontro NSS ");
    }}
    public void modificar_empleados(){
    String clave = txt_clave.getText();
    String Nombre = txt_nombre.getText();
    String ApellidoP = txt_ap.getText();
    String ApellidoM = txt_am.getText();
    String telefono = txt_telefono.getText();
    String domicilio = txt_domicilio.getText();
    String area = txt_area.getText();

    
  
    
   metodos_SQL.modificar_empleados(clave,Nombre, ApellidoP, ApellidoM, telefono, domicilio, area);
    
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_clave = new javax.swing.JLabel();
        txt_clave = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_ap = new javax.swing.JLabel();
        txt_ap = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        lbl_domicilio = new javax.swing.JLabel();
        txt_domicilio = new javax.swing.JTextField();
        lbl_am = new javax.swing.JLabel();
        txt_am = new javax.swing.JTextField();
        lbl_area = new javax.swing.JLabel();
        txt_area = new javax.swing.JTextField();
        lblinformacion = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel1_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_clave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_clave.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clave.setText("Clave de empleado:");
        getContentPane().add(lbl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 190, 60));

        txt_clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_claveActionPerformed(evt);
            }
        });
        txt_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_claveKeyReleased(evt);
            }
        });
        getContentPane().add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 180, 40));

        lbl_nombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("Nombre:");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, 60));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 180, 40));

        lbl_ap.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_ap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ap.setText("Apellido Paterno:");
        getContentPane().add(lbl_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 160, 60));

        txt_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 180, 40));

        lbl_telefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("Telefono:");
        getContentPane().add(lbl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 90, 60));

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 180, 40));

        lbl_domicilio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_domicilio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_domicilio.setText("Domicilio:");
        getContentPane().add(lbl_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 100, 60));

        txt_domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_domicilioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 180, 40));

        lbl_am.setBackground(new java.awt.Color(255, 255, 255));
        lbl_am.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_am.setForeground(new java.awt.Color(255, 255, 255));
        lbl_am.setText("Apellido Materno:");
        getContentPane().add(lbl_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 160, 60));

        txt_am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amActionPerformed(evt);
            }
        });
        getContentPane().add(txt_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, 180, 40));

        lbl_area.setBackground(new java.awt.Color(255, 255, 255));
        lbl_area.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_area.setForeground(new java.awt.Color(255, 255, 255));
        lbl_area.setText("Area:");
        getContentPane().add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 80, 60));

        txt_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_areaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 420, 180, 40));

        lblinformacion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblinformacion.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblinformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 400, 100));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 170, 70));

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jButton1.setText("modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 170, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODIFICAR EMPLEADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 580, 40));
        getContentPane().add(jLabel1_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_domicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_domicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_domicilioActionPerformed

    private void txt_amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amActionPerformed

    private void txt_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_areaActionPerformed

    private void txt_claveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claveKeyReleased

        validacion();
        
        
        
        





        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        menu_principal nuevaventana = new menu_principal();
        nuevaventana.setVisible(true);

        //para que no se acumulen las ventanas
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
modificar_empleados();
       
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificar_empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_fondo;
    private javax.swing.JLabel lbl_am;
    private javax.swing.JLabel lbl_ap;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_clave;
    private javax.swing.JLabel lbl_domicilio;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lblinformacion;
    private javax.swing.JTextField txt_am;
    private javax.swing.JTextField txt_ap;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_domicilio;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
